@deprecate testany(index::T, mask::T) where {T <: Integer} anymasked(index, mask)
@deprecate testall(index::T, mask::T) where {T <: Integer} allmasked(index, mask)
@deprecate testval(index::T, mask::T, onemask::T) where {T <: Integer} ismasked_equal(index, mask, onemask)
@deprecate takebit(index::T, ibit::Int) where T <: Integer  readbit(index, ibit)
@deprecate takebit(index::T, bits::Int...) where T <: Integer  readbit(index, bits...)
